version: '3.8'

services:
  mfa-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./dictionaries:/app/dictionaries
      - ./models:/app/models
      - ./temp:/app/temp
    environment:
      - FLASK_ENV=development
      - PORT=5000
    restart: unless-stopped 